### ISSUE TITLE
Key Error: Receive Deliver - Expiration on Options

### ISSUE THREAD

**Issue by MarLahr** [laroche/tastyworks-pnl#31]
Hi,

I encountered a "KeyError" when processing an expiration on an option.

Traceback:
![Traceback](https://user-images.githubusercontent.com/64334057/203139900-ea26f698-010c-4451-98dc-a465fb816522.PNG)

Fields in the transaction-csv
[transactions.csv](https://github.com/laroche/tastyworks-pnl/files/10059864/transactions.csv)

As a workaround i deleted those lines and ran the program again.
Now it tells me I still have open positions (I have none), but at least the tax income statement gets created correct:
![OpenPositions](https://user-images.githubusercontent.com/64334057/203141271-90568b71-714e-4150-ba2a-63d67591dfaa.PNG)

**Comment by laroche** [comment]
Your CSV transactions should be complete. Your example data shows expiration of options, but you have not
bought or sold any options before. The current code should be fairly good tested with short options, so if
this issue is not resolved by using the complete list of transactions, then you might use long options? (Then
please submit a complete use case for that setup.)

Also the list of open positions should be looked at in detail to check for missing transactions.
(I have seen reports that downloading more than 250 transactions might truncate them. ???)

best regards,

Florian La Roche

**Comment by MarLahr** [comment]
Hi, thanks for your fast reply.

[transaction_history.csv](https://github.com/laroche/tastyworks-pnl/files/10085498/transaction_history.csv)
Here is the complete list of transactions.
With this list i get the KeyError shown above.

They are mostly long options (3 of 4 options are long options) and the report contains less than 250 transactions.
The very first removed option (GOEV on 1/21/22) was bought in 2021. I guess here i need to manually add the transaction from 2021 into the CSV-file, correct?

**Comment by laroche** [comment]
Correct, add the rabnsactions from 2021 with a normal text editor to the end of the file.
(Using a spreadsheet program, the lines are often modified.)

If you combine several transaction files, you have to delete the first line of the files except for the newest date.

Does this work for you now?

best regards from Germany/Stuttgart,

Florian La Roche

**Comment by MarLahr** [comment]
I exported all trades, so no trade which was done in the year before is missing.

Now everything works fine and I get no errors.

Thank you for the fast reply and solution!

**Comment by mark-gulati** [comment]
Thank you, this was useful to me. Maybe worth it to have in a FAQ.
